# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'HexGrid.sln'
  buildConfiguration: 'Release'

steps:
- task: NuGetCommand@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Build the project - HexGrid'
  inputs:
    command: 'build'
    projects: $(solution)
    arguments: '--no-restore --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test the project'
  inputs:
    command: 'test'
    projects: $(solution)
    arguments: '--no-build --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack the project'
  inputs:
    command: 'pack'
    projects: $(solution)
    arguments: '--no-build --configuration $(buildConfiguration)'
    
- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    command: push
    publishVstsFeed: 'CryHavocPoc/CryHavocExternalPackage'
    allowPackageConflicts: true
